# Generated by Django 4.2.30 on 2026-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_category_tenant_inventorybatch_tenant_pluitem_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter')], default='piece', max_length=10),
        ),
    ]
