# Generated by Django 4.2.30 on 2026-05-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_sale_discount_type_sale_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('carton', 'Carton')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_out', 'Sale Out'), ('purchase_in', 'Purchase In'), ('receive_in', 'Receive In'), ('return_in', 'Return In'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
