# Generated by Django 4.2.30 on 2026-05-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_product_pack_qty_alter_product_reorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PLUItem',
        ),
    ]
