# Generated by Django 4.2.30 on 2026-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_delete_pluitem'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('stock__lte', models.F('reorder')), ('active', True)), fields=['tenant', 'stock'], name='pos_product_lowstock_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', '-created_at'], name='pos_sale_tenant_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', '-created_at'], name='pos_sale_cashier_recent_idx'),
        ),
    ]
