# Generated by Django 4.2.30 on 2026-05-17 23:19

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def clamp_pre_constraint_values(apps, schema_editor):
    """Existing rows may violate the new CheckConstraints (e.g. oversold
    stock < 0). Clamp the offending fields to safe values so AddConstraint
    doesn't fail on legacy data.
    """
    Product = apps.get_model('pos', 'Product')
    Product.objects.filter(stock__lt=0).update(stock=Decimal('0'))
    Product.objects.filter(price__lt=0).update(price=Decimal('0'))
    Product.objects.filter(tax_rate__lt=0).update(tax_rate=Decimal('0'))
    Product.objects.filter(tax_rate__gt=1).update(tax_rate=Decimal('1'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username_alter_user_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0010_product_pos_product_lowstock_idx_and_more'),
    ]

    operations = [
        # Clamp legacy data so the AddConstraint ops below don't reject rows
        # written before the application-level guards existed.
        migrations.RunPython(clamp_pre_constraint_values, reverse_code=noop_reverse),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('void', 'Void')], max_length=10)),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('mixed', 'Mixed')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='success', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method_hint',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.branch'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='pos_product_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='pos_product_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 1)), name='pos_product_tax_rate_bounded'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to='pos.product'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['tenant', 'valid_until', 'is_active'], name='pos_discount_lookup_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discountcode',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', '-timestamp'], name='pos_audit_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='pos_audit_target_idx'),
        ),
    ]
