# Generated by Django 4.2.30 on 2026-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_stockmovement_actor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
    ]
