# Generated by Django 4.2.30 on 2026-06-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_balance_before'),
        ('pos', '0016_stockmovement_running_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(choices=[('main', 'Main'), ('sales', 'Sales'), ('raw_material', 'Raw Material'), ('returns', 'Returns'), ('damage', 'Damage'), ('production', 'Production'), ('other', 'Other')], default='main', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales', 'Sales'), ('purchase_receiving', 'Purchase Receiving'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('returns', 'Returns'), ('damaged', 'Damaged')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_warehouses', to='accounts.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_warehouses', to='accounts.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='pos.warehouse')),
            ],
            options={
                'ordering': ['branch_id', 'role'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pos.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='pos_warehouse_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchwarehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'branch', 'warehouse', 'role'), name='pos_branchwh_active_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchwarehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('branch', 'role'), name='pos_branchwh_one_default_per_role'),
        ),
    ]
