# Generated by Django 4.2.30 on 2026-06-30 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_balance_before'),
        ('pos', '0018_purchaseinvoice_purchaseinvoiceline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='pos.warehouse'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('credit', 'Credit'), ('mixed', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method_hint',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('credit', 'Credit')], default='', max_length=10),
        ),
    ]
