# Generated by Django 4.2.30 on 2026-07-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_balance_before'),
        ('pos', '0019_sale_customer_saleitem_unit_cost_saleitem_warehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='pos.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='accounts.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='pos.warehouse')),
            ],
            options={
                'ordering': ['product_id', 'warehouse_id'],
                'indexes': [models.Index(fields=['tenant', 'warehouse'], name='pos_whstock_tenant_wh_idx'), models.Index(fields=['tenant', 'product'], name='pos_whstock_tenant_prod_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'warehouse'), name='pos_warehousestock_uniq'),
        ),
    ]
