# Generated by Django 4.2.30 on 2026-07-12 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_balance_before'),
        ('pos', '0020_warehousestock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_groups', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('factor_to_base', models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ('allow_decimal', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounts.tenant')),
                ('unit_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='pos.unitgroup')),
            ],
            options={
                'ordering': ['unit_group_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_to_base', models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ('is_base', models.BooleanField(default=False)),
                ('is_sale_unit', models.BooleanField(default=False)),
                ('is_purchase_unit', models.BooleanField(default=False)),
                ('is_recipe_unit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='pos.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='accounts.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_units', to='pos.unit')),
            ],
            options={
                'ordering': ['product_id', '-is_base', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcodeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_units', to='pos.product')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='pos.productunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_barcode_units', to='accounts.tenant')),
            ],
            options={
                'ordering': ['product_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='unitgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='pos_unitgroup_tenant_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('tenant', 'unit_group', 'name'), name='pos_unit_tenant_group_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(check=models.Q(('factor_to_base__gt', 0)), name='pos_unit_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'unit'), name='pos_productunit_tenant_product_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('product',), name='pos_productunit_one_base_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(check=models.Q(('conversion_to_base__gt', 0)), name='pos_productunit_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_base', True), _negated=True), ('conversion_to_base', 1), _connector='OR'), name='pos_productunit_base_conversion_is_1'),
        ),
        migrations.AddConstraint(
            model_name='productbarcodeunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='pos_pbu_tenant_barcode_uniq'),
        ),
    ]
