# Generated by Django 4.2.30 on 2026-07-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_balance_before'),
        ('pos', '0021_units_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pos.salescategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_categories', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'sales categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pos.inventorycategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'inventory categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='salescategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'name'), name='pos_salescat_tenant_parent_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='salescategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('tenant', 'name'), name='pos_salescat_tenant_root_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'name'), name='pos_invcat_tenant_parent_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('tenant', 'name'), name='pos_invcat_tenant_root_name_uniq'),
        ),
    ]
