# Generated by Django 4.2.30 on 2026-07-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_category_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.inventorycategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discountable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stock_item', 'Stock item'), ('ingredient', 'Ingredient'), ('prep_item', 'Prep item'), ('recipe_product', 'Recipe product'), ('resale', 'Resale'), ('packaging', 'Packaging'), ('service', 'Service'), ('bundle', 'Bundle'), ('fixed_asset', 'Fixed asset')], default='stock_item', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.salescategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_pos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'product_type'], name='pos_product_tenant_type_idx'),
        ),
    ]
