# Generated by Django 4.2.30 on 2026-07-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_add_balance_before"),
        ("pos", "0023_product_foundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductUnitTierPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["product_id", "product_unit_id", "price_tier_id"],
            },
        ),
        migrations.AddField(
            model_name="productunit",
            name="minimum_order_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("minimum_order_qty__isnull", True),
                    ("minimum_order_qty__gt", 0),
                    _connector="OR",
                ),
                name="pos_productunit_min_order_qty_positive",
            ),
        ),
        migrations.AddField(
            model_name="productunittierprice",
            name="price_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unit_prices",
                to="pos.pricetier",
            ),
        ),
        migrations.AddField(
            model_name="productunittierprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_tier_prices",
                to="pos.product",
            ),
        ),
        migrations.AddField(
            model_name="productunittierprice",
            name="product_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier_prices",
                to="pos.productunit",
            ),
        ),
        migrations.AddField(
            model_name="productunittierprice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_unit_tier_prices",
                to="accounts.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pricetier",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_tiers",
                to="accounts.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="productunittierprice",
            constraint=models.UniqueConstraint(
                fields=("product_unit", "price_tier"),
                name="pos_puttp_product_unit_price_tier_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="productunittierprice",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", 0)), name="pos_puttp_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricetier",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="pos_pricetier_tenant_name_uniq"
            ),
        ),
    ]
