# Generated by Django 4.2.30 on 2026-07-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0025_unit_standard_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoiceline",
            name="entered_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseinvoiceline",
            name="product_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_invoice_lines",
                to="pos.productunit",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="entered_qty",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="pos.productunit",
            ),
        ),
    ]
