# Generated by Django 4.2.30 on 2026-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0027_inventory_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("sale_out", "Sale Out"),
                    ("purchase_in", "Purchase In"),
                    ("receive_in", "Receive In"),
                    ("return_in", "Return In"),
                    ("adjustment", "Adjustment (legacy)"),
                    ("adjustment_in", "Adjustment In"),
                    ("adjustment_out", "Adjustment Out"),
                ],
                max_length=20,
            ),
        ),
    ]
