# Generated by Django 4.2.30 on 2026-07-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_add_balance_before"),
        ("pos", "0028_alter_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycost",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_costs",
                to="accounts.branch",
            ),
        ),
        migrations.AlterField(
            model_name="inventorycost",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_costs",
                to="pos.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycost",
            constraint=models.UniqueConstraint(
                fields=("product", "branch"), name="pos_invcost_product_branch_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True)),
                fields=("product",),
                name="pos_invcost_product_null_branch_uniq",
            ),
        ),
    ]
