# Generated by Django 4.2.30 on 2026-07-22 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_modifiergroup_modifieroption_productmodifiergroup_and_more"),
        ("pos", "0029_branch_scoped_inventory_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_items",
                to="recipes.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("sale_out", "Sale Out"),
                    ("purchase_in", "Purchase In"),
                    ("receive_in", "Receive In"),
                    ("return_in", "Return In"),
                    ("adjustment", "Adjustment (legacy)"),
                    ("adjustment_in", "Adjustment In"),
                    ("adjustment_out", "Adjustment Out"),
                    ("recipe_consume", "Recipe Consume"),
                ],
                max_length=20,
            ),
        ),
    ]
