# Generated by Django 4.2.30 on 2026-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0030_saleitem_variant_alter_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="variant_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="variant_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
