# Generated by Django 4.2.30 on 2026-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_add_balance_before"),
        ("pos", "0031_saleitem_variant_name_saleitem_variant_price"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("tenant", "sku")},
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("tenant", "barcode"),
                name="pos_product_tenant_barcode_uniq_nonempty",
            ),
        ),
    ]
