# Generated by Django 4.2.30 on 2026-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenant_address_tenant_logo_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='EGP', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
