# Generated by Django 4.2.30 on 2026-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_currency_tenant_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='show_tax_on_receipt',
            field=models.BooleanField(default=True),
        ),
    ]
