# Generated by Django 4.2.30 on 2026-05-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenant_show_tax_on_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='card_terminal_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_card_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_cash_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_wallet_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='printer_connection',
            field=models.CharField(choices=[('usb', 'USB'), ('network', 'Network'), ('bluetooth', 'Bluetooth')], default='usb', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='printer_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='printer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='scale_barcode_prefix',
            field=models.CharField(default='21', max_length=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='scale_connection',
            field=models.CharField(choices=[('serial', 'Serial'), ('usb', 'USB'), ('network', 'Network')], default='serial', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='scale_export_interval',
            field=models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Africa/Cairo', max_length=64),
        ),
    ]
