# Generated by Django 4.2.30 on 2026-05-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_card_terminal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='translation_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
