# Generated by Django 4.2.30 on 2026-05-17 23:19

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenant_translation_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists in this tenant.'}, help_text='Required. 150 chars or fewer. Unique per tenant.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('tenant', 'username')},
        ),
    ]
