# Generated by Django 4.2.30 on 2026-06-27 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tenant_receipt_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sales_warehouse_id', models.BigIntegerField(blank=True, null=True)),
                ('default_purchase_warehouse_id', models.BigIntegerField(blank=True, null=True)),
                ('default_cashbox_id', models.BigIntegerField(blank=True, null=True)),
                ('default_main_safe_id', models.BigIntegerField(blank=True, null=True)),
                ('default_price_tier_id', models.BigIntegerField(blank=True, null=True)),
                ('require_shift_for_pos', models.BooleanField(default=False)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('allow_shift_close_with_open_orders', models.BooleanField(default=False)),
                ('receipt_header', models.TextField(blank=True, default='')),
                ('receipt_footer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branch settings',
            },
        ),
        migrations.CreateModel(
            name='BranchUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_branch', models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Cashier', 'Cashier')], default='Cashier', max_length=10)),
                ('is_default_branch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'branch user assignments',
                'ordering': ['branch_id', 'user_id'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('main', 'Main'), ('store', 'Store'), ('warehouse_only', 'Warehouse Only'), ('delivery', 'Delivery'), ('kiosk', 'Kiosk'), ('other', 'Other')], default='store', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant', 'code'), name='accounts_branch_tenant_code_uniq'),
        ),
        migrations.AddField(
            model_name='branchuserassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='branchuserassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_user_assignments', to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='branchuserassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='accounts.tenant'),
        ),
        migrations.AddConstraint(
            model_name='branchuserassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'user'), name='accounts_branch_user_uniq'),
        ),
    ]
