# Generated by Django 4.2.30 on 2026-06-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_branch_master_data_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('method_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet'), ('credit', 'Credit'), ('custom', 'Custom')], db_index=True, max_length=10)),
                ('provider_name', models.CharField(blank=True, default='', max_length=80)),
                ('requires_customer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('cashbox', 'Cashbox'), ('main_safe', 'Main Safe'), ('bank', 'Bank'), ('card_settlement', 'Card Settlement'), ('wallet', 'Wallet'), ('customer_ar', 'Customer AR'), ('supplier_ap', 'Supplier AP'), ('expense', 'Expense'), ('opening_balance', 'Opening Balance'), ('other', 'Other')], db_index=True, max_length=20)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='accounts.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='accounts.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.branch')),
                ('commission_expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payment_methods', to='accounts.financialaccount')),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_payment_methods', to='accounts.financialaccount')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_links', to='accounts.paymentmethod')),
                ('settlement_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_payment_methods', to='accounts.financialaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_payment_methods', to='accounts.tenant')),
            ],
            options={
                'ordering': ['branch_id', 'payment_method_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='accounts_payment_method_tenant_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['tenant', 'account_type'], name='accounts_facct_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant', 'code'), name='accounts_financial_account_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='branchpaymentmethod',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'payment_method'), name='accounts_branch_payment_uniq'),
        ),
    ]
