# Generated by Django 4.2.30 on 2026-06-27 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_finance_payment_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document_type', models.CharField(blank=True, default='', max_length=80)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('sales_cash_in', 'Sales Cash In'), ('sales_card_in', 'Sales Card In'), ('sales_wallet_in', 'Sales Wallet In'), ('sales_credit', 'Sales Credit'), ('customer_receipt_in', 'Customer Receipt In'), ('sales_return_out', 'Sales Return Out'), ('purchase_out', 'Purchase Out'), ('supplier_payment_out', 'Supplier Payment Out'), ('supplier_ap_increase', 'Supplier AP Increase'), ('purchase_return_in', 'Purchase Return In'), ('expense_out', 'Expense Out'), ('expense_recorded', 'Expense Recorded'), ('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('cash_drop_out', 'Cash Drop Out'), ('cash_drop_in', 'Cash Drop In'), ('settlement_to_bank', 'Settlement To Bank'), ('settlement_from_card', 'Settlement From Card'), ('rounding_adjustment', 'Rounding Adjustment'), ('other', 'Other')], db_index=True, max_length=40)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('terminal_id', models.BigIntegerField(blank=True, null=True)),
                ('shift_id', models.BigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounts.financialaccount')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_movements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_movements', to='accounts.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_movements', to='accounts.tenant')),
            ],
            options={
                'ordering': ['account_id', 'id'],
                'indexes': [models.Index(fields=['tenant', 'account', 'id'], name='acct_mvmt_t_a_id_idx'), models.Index(fields=['tenant', 'branch', 'occurred_at'], name='acct_mvmt_t_b_occ_idx'), models.Index(fields=['source_document_type', 'source_document_id'], name='acct_mvmt_src_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='financialaccountmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='acct_mvmt_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='financialaccountmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='acct_mvmt_one_side_only'),
        ),
        migrations.AddConstraint(
            model_name='financialaccountmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit', 0), ('credit', 0), _negated=True), name='acct_mvmt_nonzero'),
        ),
    ]
