# Generated by Django 4.2.30 on 2026-06-27 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_supplier_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerARMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document_type', models.CharField(blank=True, default='', max_length=80)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('movement_type', models.CharField(db_index=True, max_length=40)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_movements', to='accounts.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['customer_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAPMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document_type', models.CharField(blank=True, default='', max_length=80)),
                ('source_document_id', models.BigIntegerField(blank=True, null=True)),
                ('movement_type', models.CharField(db_index=True, max_length=40)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.branch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_movements', to='accounts.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'ordering': ['supplier_id', 'id'],
                'indexes': [models.Index(fields=['tenant', 'supplier', 'id'], name='ap_mvmt_t_s_id_idx'), models.Index(fields=['tenant', 'branch', 'occurred_at'], name='ap_mvmt_t_b_occ_idx'), models.Index(fields=['source_document_type', 'source_document_id'], name='ap_mvmt_src_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierapmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ap_mvmt_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierapmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='ap_mvmt_one_side_only'),
        ),
        migrations.AddConstraint(
            model_name='supplierapmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit', 0), ('credit', 0), _negated=True), name='ap_mvmt_nonzero'),
        ),
        migrations.AddIndex(
            model_name='customerarmovement',
            index=models.Index(fields=['tenant', 'customer', 'id'], name='ar_mvmt_t_c_id_idx'),
        ),
        migrations.AddIndex(
            model_name='customerarmovement',
            index=models.Index(fields=['tenant', 'branch', 'occurred_at'], name='ar_mvmt_t_b_occ_idx'),
        ),
        migrations.AddIndex(
            model_name='customerarmovement',
            index=models.Index(fields=['source_document_type', 'source_document_id'], name='ar_mvmt_src_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerarmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ar_mvmt_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='customerarmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='ar_mvmt_one_side_only'),
        ),
        migrations.AddConstraint(
            model_name='customerarmovement',
            constraint=models.CheckConstraint(check=models.Q(('debit', 0), ('credit', 0), _negated=True), name='ar_mvmt_nonzero'),
        ),
    ]
