# Generated by Django 4.2.30 on 2026-06-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_receipt_supplier_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerarmovement',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountmovement',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='supplierapmovement',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
