# Generated by Django 4.2.30 on 2026-07-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0029_branch_scoped_inventory_cost"),
        ("accounts", "0016_add_balance_before"),
        ("recipes", "0002_recipe_recipeversion_recipeline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[("single", "Single"), ("multiple", "Multiple")],
                        default="multiple",
                        max_length=10,
                    ),
                ),
                ("min_select", models.PositiveIntegerField(blank=True, null=True)),
                ("max_select", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModifierOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "price_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifier_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="recipes.modifiergroup",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_options",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductModifierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "modifier_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="recipes.modifiergroup",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_group_links",
                        to="pos.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_modifier_groups",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModifierOptionConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entered_qty", models.DecimalField(decimal_places=3, max_digits=14)),
                ("qty_base", models.DecimalField(decimal_places=4, max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modifier_consumptions",
                        to="pos.product",
                    ),
                ),
                (
                    "component_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.productunit",
                    ),
                ),
                (
                    "modifier_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="recipes.modifieroption",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_option_consumptions",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_consumptions",
                        to="recipes.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productmodifiergroup",
            constraint=models.UniqueConstraint(
                fields=("product", "modifier_group"),
                name="recipes_prodmodgroup_product_group_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="modifieroptionconsumption",
            constraint=models.CheckConstraint(
                check=models.Q(("entered_qty", 0), _negated=True),
                name="recipes_modconsumption_entered_qty_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="modifieroptionconsumption",
            constraint=models.UniqueConstraint(
                fields=("modifier_option", "variant", "component_product"),
                name="recipes_modconsumption_option_variant_component_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="modifieroptionconsumption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("modifier_option", "component_product"),
                name="recipes_modconsumption_option_component_null_variant_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="modifieroption",
            constraint=models.UniqueConstraint(
                fields=("tenant", "modifier_group", "name"),
                name="recipes_modoption_tenant_group_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="modifiergroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="recipes_modgroup_tenant_name_uniq"
            ),
        ),
    ]
