# Generated by Django 4.2.30 on 2026-07-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_add_balance_before"),
        ("pos", "0030_saleitem_variant_alter_stockmovement_movement_type"),
        ("recipes", "0003_modifiergroup_modifieroption_productmodifiergroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleItemRecipeCostSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_recipe_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.recipeversion",
                    ),
                ),
                (
                    "sale_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_cost_snapshot",
                        to="pos.saleitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_item_recipe_cost_snapshots",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItemRecipeCostSnapshotLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_name", models.CharField(max_length=120)),
                ("qty_base", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=14)),
                ("line_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_modifier_line", models.BooleanField(default=False)),
                (
                    "component_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.product",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="recipes.saleitemrecipecostsnapshot",
                    ),
                ),
                (
                    "source_modifier_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.modifieroption",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_item_recipe_cost_snapshot_lines",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SaleItemModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_name", models.CharField(max_length=80)),
                ("price_delta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "modifier_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipes.modifieroption",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="pos.saleitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_item_modifiers",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
    ]
