# Generated by Django 4.2.30 on 2026-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_saleitemrecipecostsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitemmodifier",
            name="group_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
